name: domain-sync

on:
  # Deploy config whenever DNS changes are pushed to main.
  push:
    branches:
      - main
    paths:
      - ".github/workflows/domain-sync.yml"
      - ".github/settings.yml"
      # Only domain folders ending in dots.
      - "*.domain/*.yaml"
      - "config.yaml"

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  publish:
    name: Publish DNS config from main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - name: Install octoDNS
        run: make setup

      - name: Publish
        run: yes | make run
