name: Sync Repo Settings

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/sync-repo-settings.yml"
      - ".github/settings.yml"
      # Only domain folders ending in dots.
      - "*.domain/*.yaml"
      - "config.yaml"
  schedule:
    # See: https://crontab.guru/#55_2_*_*_*
    - cron: "55 2 * * *"

jobs:
  sync-repo-settings:
    runs-on: ubuntu-latest

    steps:
      - name: Generate ephemeral GH App Token
        id: workflow-token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          # See: https://github.com/apps/repo-settings-sync-g0v-network
          application_id: 194297
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY_BASE64 }}

      - uses: actions/checkout@v2

      - uses: exivity/actions/sync-defaults@main
        with:
          gh-token: ${{ steps.workflow-token.outputs.token }}
